version: '3.9'

services:
  postgis:
    build:
      context: ./.config/postgis 
    image: {{cookiecutter.project_slug}}_postgis
    container_name: {{cookiecutter.project_slug}}_postgis
    env_file: 
      - ./.config/postgis/postgis.env 
    volumes: 
      - postgis_data:/var/lib/postgresql/data
      - ./data:/work
    hostname: {{cookiecutter.project_slug}}_postgis
    networks:
      - postgrest_network
    ports: 
      - {{cookiecutter.postgis_port}}:5432
    working_dir: /work

  pgadmin:
    build:
      context: ./.config/pgadmin4
    image: {{cookiecutter.project_slug}}_pgadmin4
    container_name: {{cookiecutter.project_slug}}_pgadmin4
    env_file: 
      - ./.config/pgadmin4/pgadmin.env
    volumes: 
      - pgadmin4_data:/var/lib/pgadmin
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_pgadmin4
    networks: 
      - postgrest_network
    ports: 
      - {{cookiecutter.pgadmin_port}}:80
  
  tileserver:
    build: 
      context: .
      dockerfile: ./.config/pg_tileserv/Dockerfile
    image: {{cookiecutter.project_slug}}_pg_tileserv
    container_name: {{cookiecutter.project_slug}}_pg_tileserv
    env_file: 
      - ./.config/pg_serv.env
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_pg_tileserv
    networks: 
      - postgrest_network
    ports: 
      - {{cookiecutter.tileserv_port}}:7800

  featureserver:
    build: 
      context: .
      dockerfile: ./.config/pg_featureserv/Dockerfile
    image: {{cookiecutter.project_slug}}_pg_featureserv
    container_name: {{cookiecutter.project_slug}}_pg_featureserv
    env_file: 
      - ./.config/pg_serv.env
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_pg_featureserv
    networks: 
      - postgrest_network
    ports: 
      - {{cookiecutter.featureserv_port}}:9000
  
  postgrest:
    # build:
    #   context: ./.config/postgrest
    image: postgrest/postgrest:v10.1.1
    container_name: {{cookiecutter.project_slug}}_postgrest
    env_file:
      - ./.config/postgrest/postgrest.env
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_postgrest
    networks:
      - postgrest_network
    ports:
      - 3000:3000
  
  # swagger:
  #   image: swaggerapi/swagger-ui
  #   container_name: {{cookiecutter.project_slug}}_swagger
  #   env_file:
  #     - ./.config/swagger/swagger.env
  #   depends_on:
  #     - postgrest
  #   hostname: {{cookiecutter.project_slug}}_swagger
  #   networks:
  #     - postgrest_network
  #   ports:
  #     - "8080:8080"

networks: 
  postgrest_network:

volumes: 
  postgis_data:
  pgadmin4_data: