version: '3.9'

services:
  postgis:
    build:
      context: ./.config/postgis 
    image: {{cookiecutter.project_slug}}_postgis
    container_name: {{cookiecutter.project_slug}}_postgis
    env_file: 
      - ./.config/postgis/postgis.env 
    volumes: 
      - postgis_data:/var/lib/postgresql/data
      - ./data:/work
    hostname: {{cookiecutter.project_slug}}_postgis
    networks:
      - barebones_network
    ports: 
      - {{cookiecutter.postgis_port}}:5432
    working_dir: /work

  pgadmin:
    build:
      context: ./.config/pgadmin4
    image: {{cookiecutter.project_slug}}_pgadmin4
    container_name: {{cookiecutter.project_slug}}_pgadmin4
    env_file: 
      - ./.config/pgadmin4/pgadmin.env
    volumes: 
      - pgadmin4_data:/var/lib/pgadmin
      # - ./data/pgadmin4sql:/var/lib/pgadmin/storage
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_pgadmin4
    networks: 
      - barebones_network
    ports: 
      - {{cookiecutter.pgadmin_port}}:80

  pgloader:
    image: dimitri/pgloader:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: {{cookiecutter.project_slug}}_pgloader
    volumes: 
      - ./data:/work
    hostname: {{cookiecutter.project_slug}}_pgloader
    networks:
      - barebones_network
    working_dir: /work

networks: 
  barebones_network:

volumes: 
  postgis_data:
  pgadmin4_data: