version: '3.9'

services:
  postgis:
    build:
      context: ./.config/postgis 
    image: {{cookiecutter.project_slug}}_postgis
    container_name: {{cookiecutter.project_slug}}_postgis
    env_file: 
      - ./.config/postgis/postgis.env 
    volumes: 
      - {{cookiecutter.project_slug}}_postgis_data:/var/lib/postgresql/data
      - ./local_data/geospatial:/work
    hostname: {{cookiecutter.project_slug}}_postgis
    networks:
      - {{cookiecutter.project_slug}}_network
    ports: 
      - {{cookiecutter.postgis_port}}:5432

networks: 
  {{cookiecutter.project_slug}}_network:

volumes: 
  {{cookiecutter.project_slug}}_postgis_data:
  {{cookiecutter.project_slug}}_pgadmin4:
