version: '3.9'

services:
  postgis:
    build:
      context: ./.config/postgis 
    image: {{cookiecutter.project_slug}}_postgis
    container_name: {{cookiecutter.project_slug}}_postgis
    env_file: 
      - ./.config/postgis/postgis.env 
    volumes: 
      - postgis_data:/var/lib/postgresql/data
      - ./data:/work
    hostname: {{cookiecutter.project_slug}}_postgis
    networks:
      - mapping_network
    ports: 
      - {{cookiecutter.postgis_port}}:5432
    working_dir: /work

  pgadmin:
    build:
      context: ./.config/pgadmin4
    image: {{cookiecutter.project_slug}}_pgadmin4
    container_name: {{cookiecutter.project_slug}}_pgadmin4
    env_file: 
      - ./.config/pgadmin4/pgadmin.env
    volumes: 
      - pgadmin4:/var/lib/pgadmin
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_pgadmin4
    networks: 
      - mapping_network
    ports: 
      - {{cookiecutter.pgadmin_port}}:80

  # pgloader:
  #   image: dimitri/pgloader:latest
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   container_name: {{cookiecutter.project_slug}}_pgloader
  #   volumes: 
  #     - ./data:/work
  #   hostname: {{cookiecutter.project_slug}}_pgloader
  #   networks:
  #     - mapping_network
  #   working_dir: /work

  # gdal:
  #   image: osgeo/gdal:alpine-small-latest
  #   stdin_open: true # docker run -i
  #   tty: true        # docker run -t
  #   container_name: {{cookiecutter.project_slug}}_gdal
  #   volumes: 
  #     - ./data:/work
  #   hostname: {{cookiecutter.project_slug}}_gdal
  #   networks:
  #     - mapping_network
  #   working_dir: /work

  tileserver:
    build: 
      context: .
      dockerfile: ./.config/pg_tileserv/Dockerfile
    image: {{cookiecutter.project_slug}}_pg_tileserv
    container_name: {{cookiecutter.project_slug}}_pg_tileserv
    env_file: 
      - ./.config/pg_serv.env
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_pg_tileserv
    networks: 
      - mapping_network
    ports: 
      - {{cookiecutter.tileserv_port}}:7800

  featureserver:
    build: 
      context: .
      dockerfile: ./.config/pg_featureserv/Dockerfile
    image: {{cookiecutter.project_slug}}_pg_featureserv
    container_name: {{cookiecutter.project_slug}}_pg_featureserv
    env_file: 
      - ./.config/pg_serv.env
    depends_on:
      - postgis
    hostname: {{cookiecutter.project_slug}}_pg_featureserv
    networks: 
      - mapping_network
    ports: 
      - {{cookiecutter.featureserv_port}}:9000

networks: 
  mapping_network:

volumes: 
  postgis_data:
  pgadmin4_data:
